version: '2'
services:
  # Fusio container
  fusio:
    # build local version
    # image: fusio/fusio
    build: .
    environment:
      FUSIO_PROJECT_KEY: "42eec18ffdbffc9fda6110dcc705d6ce"
      FUSIO_HOST: "acme.com"
      FUSIO_URL: "http://acme.com"
      FUSIO_APPS_URL: "http://apps.acme.com"
      FUSIO_ENV: "prod"
      FUSIO_DB_NAME: "fusio"
      # database driver
      FUSIO_DB_DRIVER: "pdo_pgsql"
      FUSIO_DB_USER: "fusio"
      FUSIO_DB_PW: "dphYFbKN"
      FUSIO_DB_HOST: "postgres_fusio"
      # token expiration params (needs to be changed!)
      FUSIO_EXPIRE_IMPLICIT: "P365D"
      FUSIO_EXPIRE_APP: "P365D"
      FUSIO_EXPIRE_BACKEND: "P365D"
      FUSIO_EXPIRE_CONSUMER: "P365D"
      FUSIO_BACKEND_USER: "demo"
      FUSIO_BACKEND_EMAIL: "demo@fusio-project.org"
      FUSIO_BACKEND_PW: "75dafcb12c4f"
      FUSIO_VERSION: "master"
      PROVIDER_FACEBOOK_KEY: ""
      PROVIDER_FACEBOOK_SECRET: ""
      PROVIDER_GOOGLE_KEY: ""
      PROVIDER_GOOGLE_SECRET: ""
      PROVIDER_GITHUB_KEY: ""
      PROVIDER_GITHUB_SECRET: ""
      RECAPTCHA_KEY: ""
      RECAPTCHA_SECRET: ""
    links:
      - postgres_fusio
    ports:
      - "80:8080"
    volumes:
      - ./apps:/var/www/html/fusio/apps
      - ./public:/var/www/html/fusio/public

  # Fusio system database
  postgres_fusio:
    image: postgres:10.13
    environment:
      # MYSQL_ROOT_PASSWORD: "7f3e5186032a"
      POSTGRES_USER: "fusio"
      POSTGRES_PASSWORD: "dphYFbKN"
      POSTGRES_DB: "fusio"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    ports:
      - "5432:5432"
    volumes:
      - ./db:/var/lib/postgresql/data/pgdata
